### ISSUE TITLE
document how to transfer a project to puppet community

### ISSUE THREAD

**Issue by igalic** [puppet-community/puppet-community.github.io#1]
what are the (pre) conditions to transferring a project?

What range of licenses do we accept?
How do we guarantee that they cleared?

**Comment by nibalizer** [comment]
@ryanycoleman made this https://gist.github.com/ryanycoleman/c83f1c0047e8cb4de92e

**Comment by igalic** [comment]
i love step 3.

**Comment by liamjbennett** [comment]
Also need to make sure that any webhooks (other than travis) are removed. We found our repos kept talking to our internal hipchat even after migration.

**Comment by nibalizer** [comment]
HAHHAHAHAHHAHA

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-community.github.io/pull/11/files

**Comment by igalic** [comment]
\o/

**Comment by hydeenicole** [comment]
Hellow my names hydee. i worked hard all my life. my car broke. I'm torn I'm looken for more online jobs or a derection. I'm 29 my family work are so imortant and this is geting worse feel free if anyone knows of any help pleasw 8143124068, thank you so much xoxo

**Comment by hydeenicole** [comment]
Gues ur two comments were ritten from uk see tom. how fun u both will faint and ul never drice again ever watch little kids. ur prety brave.

**Comment by hydeenicole** [comment]
Lol I'm a super model in ny. but I'm traing this sight ur infos in ur friends is and ul deel w it my job there done .

**Comment by hydeenicole** [comment]
Hey call me a imigriant after i right of looking asking as u sit and get high guess what i new who i was studing there actions bf i post. fuck off now

**Comment by vmbrasseur** [comment]
@igalic is standing here over my shoulder telling me to close this. So, uh, OK.
