### ISSUE TITLE
setup a module-sync for puppet community

### ISSUE THREAD

**Issue by igalic** [puppet-community/puppet-community.github.io#5]
we should probably offer (our own?) [module sync](https://github.com/puppetlabs/modulesync), to keep puppet-community module's up-to-date with the current recommended technology.

**Comment by nibalizer** [comment]
Here is some less than optimal scripting around the secrets:

https://github.com/puppet-community/plumbing/blob/travis/share/travis_secrets and puppet-community/plumbing#1

**Comment by igalic** [comment]
so i thought i should move this issue to plumbing, then realised, this is @github. you can't do that.

**Comment by igalic** [comment]
btw, closing as per our [CONTRIBUTING.md](https://github.com/puppet-community/puppet-community.github.io/blob/master/CONTRIBUTING.md) since this repository is for issues with the community, and we haven't really done anyone any wrong yet ;)
